services:
  - type: web
    name: toto-ecommerce
    runtime: docker
    dockerfilePath: ./Demo_Ecommerce/Dockerfile
    dockerContext: ./Demo_Ecommerce
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=demoecommerce.db"
